<?php        
$this->headTitle($this->title);
?>

<table class="table table-hover">
  <thead>
	<tr>
		<th scope="col" style="display: none;">ИД</th>
		<th scope="col" class="date">Дата</th>
		<th scope="col">Запрос</th>
		<th scope="col" class="se">Поисковик</th>
		<th scope="col" class="number">Позиция</th>
		<th scope="col" class="links">Ссылок</th>
	</tr>
 </thead>
 <tbody>
 
<?php foreach($this->position as $position) : ?>
	<TR>
		<TD style="display: none;"><?php echo $position->idquery; ?></TD>
		<TD><?php echo $position->date; ?></TD>
		<TD><?php echo $position->name; ?></TD>
		<TD><?php echo $position->se; ?></TD>
		<TD><?php echo $position->number; ?></TD>
		<TD><?php echo $position->links; ?></TD>
	</TR>
<?php endforeach; ?>

<?php if(!count($this->position)): ?>
<TR>
<TD colspan="5">Нет данных</TD>
</TR>
<?php endif; ?>

</tbody>
</TABLE>

<?php echo $this->paginationControl($this->position, 'Sliding', 'pagination.phtml'); ?>


